Update and rename nativeCompile.yml to build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,9 +29,29 @@ jobs:
         path: cli/build/libs/acdasm-*.jar
         if-no-files-found: error
 
+  # This is a crude license header check. The ones I tested were susceptible to whitespace differences
+  # and I never got them to work. My primary goal is to ensure the headers exist, so this suffices.
+  license-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v7
+      - name: Look for license phrase
+        run: |
+          outfile=$(mktemp)
+          find . -name "*.java" | xargs grep -L "GNU General Public License" > ${outfile}
+          if [ -s "${outfile}" ]
+          then
+            echo "License headers missing on the following files:"
+            cat ${outfile}
+            exit 1
+          else
+            echo "License headers appear to be valid!"
+          fi
+
   build-native:
     name: acdasm on ${{ matrix.os }}-${{ matrix.arch }}
-    needs: [build-java]
+    needs: [build-java, license-check]
     runs-on: ${{ matrix.label  }}
     strategy:
       matrix:
